# Generated by Django 3.1.6 on 2021-02-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
