# Generated by Django 3.1.6 on 2021-02-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseapi',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='responseapi',
            name='temp_max',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='responseapi',
            name='temp_min',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
