# Generated by Django 3.1.6 on 2021-02-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210215_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseapi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
